//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inzynierka_aplikacja.MainDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InzynierkaDBEntities : DbContext
    {
        public InzynierkaDBEntities()
            : base("name=InzynierkaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrator { get; set; }
        public virtual DbSet<GrupaNaprawcza> GrupaNaprawcza { get; set; }
        public virtual DbSet<Handlowiec> Handlowiec { get; set; }
        public virtual DbSet<Miejsce_instalacji> Miejsce_instalacji { get; set; }
        public virtual DbSet<PamiecLogowania> PamiecLogowania { get; set; }
        public virtual DbSet<Podatnik> Podatnik { get; set; }
        public virtual DbSet<Serwisant> Serwisant { get; set; }
        public virtual DbSet<SerwisUrzadzenia> SerwisUrzadzenia { get; set; }
        public virtual DbSet<UrzadSkarbowy> UrzadSkarbowy { get; set; }
        public virtual DbSet<Urzadzenie> Urzadzenie { get; set; }
        public virtual DbSet<Uslugi> Uslugi { get; set; }
    }
}
