//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inzynierka_aplikacja.MainDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Podatnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Podatnik()
        {
            this.Urzadzenie = new HashSet<Urzadzenie>();
        }
    
        public int podatnik_id { get; set; }
        public int urzad_id { get; set; }
        public string nazwa { get; set; }
        public string symbol { get; set; }
        public string nip { get; set; }
        public string wojewodztwo { get; set; }
        public string miasto { get; set; }
        public string ulica { get; set; }
        public string kod_pocztowy { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
    
        public virtual UrzadSkarbowy UrzadSkarbowy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urzadzenie> Urzadzenie { get; set; }
    }
}
