//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inzynierka_aplikacja.MainDB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class UrzadSkarbowy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UrzadSkarbowy()
        {
            this.Podatnik = new HashSet<Podatnik>();
        }
    
        public int urzad_id { get; set; }
        [Column("Nazwa")]
        public string nazwa { get; set; }
        [Column("Miasto")]
        public string miasto { get; set; }
        [Column("Ulica")]
        public string ulica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Podatnik> Podatnik { get; set; }
    }
}
